version: "3.8"

services:
  db:
    image: mysql:8.0
    build: ./mysql/
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app         
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d/
    #   - ./mysql/conf.d:/etc/mysql/conf.d
  
  user-product:
    container_name: user-product
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true    
    volumes:
      - ./api:/app   
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - db
      