version: '3'

services:
  myapp1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  myapp2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"

  load-balancer:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
    depends_on:
      - myapp1
      - myapp2
